In [2]:
import torch

### Creating tensors

In [3]:
# Scalar - single number
scalar = torch.tensor(5)
scalar

tensor(5)

checking the dimension of tensor (number of square brackets) 

In [4]:
scalar.ndim 

0

retrieve the number from the tensor?

In [5]:
scalar.item()

5

In [6]:
# Vector - single dimension tensor cantain many numbers
vector = torch.tensor([3, 4])
vector 

tensor([3, 4])

In [7]:
vector.ndim

1

shape - elements inside the square brackets

In [8]:
vector.shape 

torch.Size([2])

In [9]:
# Matrix - Vectors with more dimensions
MATRIX = torch.tensor([[1, 2],
                      [3, 4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [10]:
MATRIX.ndim 

2

In [11]:
MATRIX.shape 

torch.Size([2, 2])

tensors

In [12]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3], 
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape 
# TENSOR.shape([1, 3, 3]) - means this is a 1 dimension of 3 by 3. 

torch.Size([1, 3, 3])

### Random Tensors

In [20]:
random_tensor = torch.rand(1, 3, 3)
random_tensor, random_tensor.ndim 

(tensor([[[0.1220, 0.4005, 0.7494],
          [0.7931, 0.0793, 0.1410],
          [0.0571, 0.0425, 0.0452]]]),
 3)

### Creating a range

In [23]:
zero_to_ten = torch.arange(start=0, end=11, step=1)   # Runs till end-1
zero_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])