In [1]:
import torch

### Creating tensors

In [3]:
# Scalar - single number
scalar = torch.tensor(5)
scalar

tensor(5)

checking the dimension of tensor (number of square brackets) 

In [4]:
scalar.ndim 

0

retrieve the number from the tensor?

In [5]:
scalar.item()

5

In [6]:
# Vector - single dimension tensor cantain many numbers
vector = torch.tensor([3, 4])
vector 

tensor([3, 4])

In [7]:
vector.ndim

1

shape - elements inside the square brackets

In [8]:
vector.shape 

torch.Size([2])

In [9]:
# Matrix - Vectors with more dimensions
MATRIX = torch.tensor([[1, 2],
                      [3, 4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [10]:
MATRIX.ndim 

2

In [11]:
MATRIX.shape 

torch.Size([2, 2])

tensors

In [12]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3], 
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape 
# TENSOR.shape([1, 3, 3]) - means this is a 1 dimension of 3 by 3. 

torch.Size([1, 3, 3])

### Random Tensors

In [20]:
random_tensor = torch.rand(1, 3, 3)
random_tensor, random_tensor.ndim 

(tensor([[[0.1220, 0.4005, 0.7494],
          [0.7931, 0.0793, 0.1410],
          [0.0571, 0.0425, 0.0452]]]),
 3)

### Creating a range

In [23]:
zero_to_ten = torch.arange(start=0, end=11, step=1)   # Runs till end-1
zero_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Tensor datatypes

In [ ]:
# Default is float32 (float)
float_32_tensor = torch.tensor([1.2, 3.5, 6.4], 
                               dtype=None,  # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type ("cpu", "cuda")
                               requires_grad=False) # if True, operations performed on the tensor are recorded 
float_32_tensor, float_32_tensor.dtype

(tensor([1.2000, 3.5000, 6.4000]), torch.float32)

In [27]:
# float64 = double
float_64_tensor = torch.tensor([2.4, 24.64], 
                               dtype=torch.float64)
float_64_tensor, float_64_tensor.dtype

(tensor([ 2.4000, 24.6400], dtype=torch.float64), torch.float64)

### Manipulating tensors (Tensor Operations)

In [2]:
tensor = torch.rand(2, 4)
tensor

tensor([[0.9139, 0.1193, 0.9382, 0.1601],
        [0.1039, 0.1136, 0.9346, 0.6225]])

In [8]:
# tensor + 2
# torch.add(tensor, 2)
# tensor * 2
# torch.mul(tensor, 2)

### Matrix Multiplication

In [ ]:
tensor1 = torch.rand(3, 4)
tensor2 = torch.rand(4, 3)
# tensor1 @ tensor2             # Slower
torch.matmul(tensor1, tensor2)  # Faster

tensor([[1.4249, 0.6887, 0.6918],
        [0.5119, 0.4270, 0.4512],
        [0.7573, 0.8203, 0.7282]])

### Transpose (to change the dimensions of a matrix)

In [ ]:
t1 = torch.tensor([[1, 2, 4], 
                  [3, 5, 7]])

t2 = torch.tensor([[2, 6, 7],
                  [6, 2, 6]])

print(f"Origina tensors shape are : {t1.shape} and {t2.shape}, which can't get multiply")
print("Shape after taking the transpose of the second tensor : \n")

print(f"{t1.shape} and {t2.T.shape}")

print("\nFinal Output")
print(f"{torch.matmul(t1, t2.T)}")

Origina tensors shape are : torch.Size([2, 3]) and torch.Size([2, 3]), which can't get multiply
Shape after taking the transpose of the second tensor : 

torch.Size([2, 3]) and torch.Size([3, 2])

Final Output
tensor([[42, 34],
        [85, 70]])


### Reshaping, stacking, squeezing and unsqueezing

In [29]:
import torch 
x = torch.arange(1., 7.)
x, x.shape 

(tensor([1., 2., 3., 4., 5., 6.]), torch.Size([6]))

In [35]:
# Reshaping (Reshapes input to shape (if compatible), can also use torch.Tensor.reshape().)
x_reshaped = x.reshape(1, 6)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6.]]), torch.Size([1, 6]))

In [7]:
# View (Returns a view of the original tensor in a different shape but shares the same data as the original tensor.)
z = x.view(5, 2)
# z, z.shape 

In [10]:
# Stacking (Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size)
s = torch.stack([x, x, x])
s

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [36]:
# Squeezing (Squeezes input to remove all the dimenions with value 1)
print(f"Before squeezing x_reshaped : {x_reshaped} and shape : {x_reshaped.shape}") 
x_reshaped_squeezed = x_reshaped.squeeze()
print(f"After squeezing x_reshaped : {x_reshaped_squeezed} and shape : {x_reshaped_squeezed.shape}")

Before squeezing x_reshaped : tensor([[1., 2., 3., 4., 5., 6.]]) and shape : torch.Size([1, 6])
After squeezing x_reshaped : tensor([1., 2., 3., 4., 5., 6.]) and shape : torch.Size([6])


In [46]:
# Unsqueezing (Opposite of squeezing)
print(f"Afer squeezing : x_reshaped : {x_reshaped_squeezed} and shape : {x_reshaped_squeezed.shape}")
x_unsqueezed = x_reshaped_squeezed.unsqueeze(dim=0)
print(f"After unsqueezing, x_rechaped : {x_unsqueezed} and shape : {x_unsqueezed.shape}")

Afer squeezing : x_reshaped : tensor([1., 2., 3., 4., 5., 6.]) and shape : torch.Size([6])
After unsqueezing, x_rechaped : tensor([[1., 2., 3., 4., 5., 6.]]) and shape : torch.Size([1, 6])


In [2]:
# Permuting (arranging) (Returns a view of the original input with its dimensions permuted (rearranged) to dims)
import torch 
x_original = torch.rand(size=(223, 34, 2))
print(f"Original shape is : {x_original.shape}")

x_permuted = x_original.permute(2, 0, 1)   # 2 to 0, 0 to 1 and 1 to 2
print(f"After permuted : {x_permuted.shape}")

Original shape is : torch.Size([223, 34, 2])
After permuted : torch.Size([2, 223, 34])


### Indexing 

In [13]:
x = torch.arange(1., 10.).reshape(1, 3, 3)
x, x.shape

(tensor([[[1., 2., 3.],
          [4., 5., 6.],
          [7., 8., 9.]]]),
 torch.Size([1, 3, 3]))

In [17]:
# x[0]
x[:]

tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])

In [18]:
# Index on x to return 9
x[:, 2, 2]

tensor([9.])

In [19]:
# Index on x to return 3, 6, 9
x[:, :, 2]

tensor([[3., 6., 9.]])

### PyTorch tensors & NumPy

In [24]:
# Numpy to tensor 
import numpy as np
numpy_array = np.array([2, 4, 1])
tensor = torch.from_numpy(numpy_array)
numpy_array, tensor
# tensor.dtype  # Default dtype will be float64  

(array([2, 4, 1]), tensor([2, 4, 1]))

In [27]:
# Tensor to numpy
tensor2 = torch.arange(2, 11)
numpy_array2 = tensor2.numpy()

tensor2, numpy_array2  # default dtype is int64

(tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([ 2,  3,  4,  5,  6,  7,  8,  9, 10]))