In [11]:
import torch

### Creating tensors

In [12]:
# Scalar - single number
scalar = torch.tensor(5)
scalar

tensor(5)

checking the dimension of tensor (number of square brackets) 

In [13]:
scalar.ndim 

0

retrieve the number from the tensor?

In [14]:
scalar.item()

5

In [15]:
# Vector - single dimension tensor cantain many numbers
vector = torch.tensor([3, 4])
vector 

tensor([3, 4])

In [16]:
vector.ndim

1

shape - elements inside the square brackets

In [17]:
vector.shape 

torch.Size([2])

In [20]:
# Matrix - Vectors with more dimensions
MATRIX = torch.tensor([[1, 2],
                      [3, 4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [21]:
MATRIX.ndim 

2

In [22]:
MATRIX.shape 

torch.Size([2, 2])

tensors

In [23]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3], 
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [26]:
TENSOR.shape 
# TENSOR.shape([1, 3, 3]) - means this is a 1 dimension of 3 by 3. 

torch.Size([1, 3, 3])