NumPy importing and making an array

In [8]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([[34, 56, 78], [876, 353, 77]])
a.shape
# print(b)
# b.shape

(3,)

Accessing/Changing elements, rows and columns

In [12]:
import numpy as np
a = np.array([[6, 7, 2, 8, 1, 87], [12, 65, 12, 67, 87, 45]])

#a[row, column] for the element
num = a[1, 1]
print(num)
print(a[1, :])

65
[12 65 12 67 87 45]


Building this array using numpy functions
<img src = "image.png" style="width:200px;height:200px">

In [8]:
import numpy as np
a = np.ones((5,5))
# print(a)
b = np.zeros((3, 3))
b[1, 1] = 9
# print(b)
a[1:4, 1:4] = b
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Linear Algebra

In [11]:
# Matrix Multiplication
import numpy as np
a = np.ones((4, 5))
print(a)
b = np.full((5, 10), 2)
print(b)

c = np.matmul(a, b)
print(c)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2]]
[[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]]
